
services:
  caddy:
    image: caddy:2.10.2
    depends_on: 
      checker:
        condition: service_started
    restart: unless-stopped
    command: sh -c "sleep 5 && caddy run --config /etc/caddy/Caddyfile --adapter caddyfile"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

  checker:
    build: 
      context: ../assets/checker
    container_name: checker
    restart: unless-stopped
    expose:
      - "9000"
    environment: 
      - PYTHONUNBUFFERED=1
    volumes:
      - ../assets/checker/domains:/app/domains:ro 

  website:
    build: .
    expose:
      - "80"                  
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
