# Docker compose file for caddy server + site container
services:
  caddy:
    image: caddy:2.10.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

  checker:
    build: 
      context: ../assets/checker
    container_name: checker
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - ./assets/checker/domains:/app/domains:ro 

  website:
    build: .
    expose:
      - "80"                  
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
